### ISSUE TITLE
Double spacing for PDFs in LaTeX

### ISSUE THREAD

**Issue by christophergandrud** [HertieDataScience2014/SyllabusAndLectures#20]
It occurred to me that you cannot easily create PDFs with double spacing in R Markdown. So I submitted a pull request to the [rmarkdown](https://github.com/rstudio/rmarkdown) repo adding this capability. 

If you download the GitHub version of R Markdown now you will be able to use double spacing (the new CRAN version should be out soon-ish):

```{S}
devtools::install_github('rstudio/rmarkdown')
```

Then in the YAML header of your .Rmd file use `setspace: doublespacing`. For example:

```{yaml}
---
title: "Untitled"
author: "Christopher Gandrud"
date: "25 October 2014"
setspace: doublespacing
output: pdf_document
---
```

**Comment by Zigzig** [comment]
Hi, How to download the Github version of rmarkdown?

**Comment by christophergandrud** [comment]
@Zigzig I'm unclear about what you are talking about.

**Comment by klocey** [comment]
Thanks for this @christophergandrud!

**Comment by christophergandrud** [comment]
:+1:
