### ISSUE TITLE
Installing rCharts package problems

### ISSUE THREAD

**Issue by oliverbott** [HertieDataScience2014/SyllabusAndLectures#25]
Hi everybody,
I am wondering whether you guys are also having issues with installing the 'rCharts' package for R.

When using `install.packages("rCharts")` I get the following error message:

```{r}
Warning in install.packages :
  package ‘rCharts’ is not available (for R version 3.1.1) 
```

When trying to use the code `require(devtools)` and `install_github('rCharts', 'ramnathv')` from the website http://ramnathv.github.io/rCharts/ I get:

```{r}
Downloading github repo ramnathv/rCharts@master
Installing rCharts
"C:/PROGRA~1/R/R-31~1.1/bin/i386/R" --vanilla CMD INSTALL  \
  "C:\Users\a6p\AppData\Local\Temp\Rtmp8qMYZJ\devtools127413d7605b\ramnathv-rCharts-929875d"  \
  --library="C:/Users/a6p/Documents/R/win-library/3.1" --install-tests 

* installing *source* package 'rCharts' ...
** R
** demo
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
ERROR: lazy loading failed for package 'rCharts'
* removing 'C:/Users/a6p/Documents/R/win-library/3.1/rCharts'
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use ramnathv/rCharts 
```

Have you been able to install the rCharts package? Can you help out?
Thanks a lot.

**Comment by fzhang988** [comment]
To whom it may concern:
I tried to follow the instruction on this website: http://ramnathv.github.io/rCharts/
Here is my R console information:

> install.packages('Rcpp')
> install_github('rCharts', 'ramnathv')

Downloading github repo ramnathv/rCharts@master
Installing rCharts
"C:/PROGRA~1/R/R-31~1.1/bin/i386/R" --vanilla CMD INSTALL "C:/Users/Administrator/AppData/Local/Temp/RtmpAxG5xa/devtools23d4d8e3233/ramnathv-rCharts-389e214" --library="C:/Program  \
  Files/R/R-3.1.1/library" --install-tests 

* installing *source* package 'rCharts' ...

** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded

* DONE (rCharts)
Warning message：
Username parameter is deprecated. Please use ramnathv/rCharts 

> names(iris) = gsub("\\.", "", names(iris))
> rPlot(SepalLength ~ SepalWidth | Species, data = iris, color = 'Species', type = 'point')
ERROR: No"rPlot" function

My question: Why is there No"rPlot" function?

Thanks!

**Comment by christophergandrud** [comment]
In the code above it doesn't look like you've loaded the package (`library(rCharts)`). I would give that a shot first.

**Comment by fzhang988** [comment]
Now, it worked. Thanks!
